server:
  port: 9999
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri:
          username:
          password:
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8866/eureka